#!/usr/bin/env python
"""
Usage: wiva <url> [ <revision> ] [ --verbose ] [ --debug ]
"""
# coding=utf-8
import docopt
import logging
import requests
from urlparse import urlparse
from wikitext.lexer import tokenize
from wikitext.parser import parse


logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.WARNING)

def get_wikitext(url):
    url_parse_result = urlparse(url)
    article = url_parse_result.path
    if article.startswith('/wiki/'):
        article = article[5:]
    article = article.lstrip('/')
    wikitext_url = "%s/api.php?action=parse&prop=wikitext&page=%s&format=json" % (
        url_parse_result.scheme + "://" + url_parse_result.hostname, article)
    r = requests.get(wikitext_url)
    return r.json()["parse"]["wikitext"]["*"]

def cli(arguments):
    if arguments['--debug']:
        logging.root.setLevel(logging.DEBUG)
    url = arguments['<url>']
    wikitext = get_wikitext(url)
    if arguments['--verbose']:
        print "Wikitext:"
        print
        print wikitext
        print

    if arguments['--verbose']:
        print "Tokens:"
        print
        print tokenize(wikitext)
        print

    print parse(wikitext)


if __name__ == '__main__':
    arguments = docopt.docopt(__doc__)
    cli(arguments)

__author__ = 'alistra'
